github: [metadata]

title: "mnote"
lang: "en_US"
encoding: UTF-8

markdown: kramdown
kramdown:
  input:  GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

theme: jekyll-theme-cayman

paginate: 10
paginate_path: ":num"

plugins: [github-pages, jekyll-paginate]
